### ISSUE TITLE
Pre-install pak?

### ISSUE THREAD

**Issue by krlmlr** [rocker-org/rspm#1]
The pak package is now dependency-free (by bundling all of its dependencies into its own binary). This gives the best experience of installing packages from RSPM on Linux. Should we add

```
RUN R -q -e 'install.packages("pak")'
```

or perhaps

```
RUN r -e 'install.packages("pak")'
```

to this Dockerfile, and document this?

**Comment by eddelbuettel** [comment]
Maybe, maybe not. I wrote this one as a baseline to compare with `r-bspm` and both operate via `install.packages()`.

**Comment by eddelbuettel** [comment]
Using the 20.04 container I just

- installed `pak` and then used it to install `nanotime` and its handful of dependencies
- did the same with just `install.packages("nanotime")`

The base R approach was faster: 12s, relative to 18s for `pak` (and _not_ counting the extra time to install `pak` first) so :man_shrugging: .  I am sure it has its fans but it doesn't yet come across as that earth-shattering.   So I will keep this container as is and rely on `install.packages()`.  Thanks for the suggestion though.

**Comment by krlmlr** [comment]
Thanks for considering and for measuring this, good to know -- "best experience" starts kicking in when dependencies are more than a handful. RSPM takes quite some time to respond to each query, and pak works around this by issuing queries simultaneously.
